# Constants
NUM_COLORS = 4
NUM_CARDS_PER_COLOR = 13
NUM_CARDS_PER_DECK = NUM_COLORS * NUM_CARDS_PER_COLOR

PID_IN_DECK_CARD = -2
PID_COMMUNITY_CARD = -1

# Color values
COL_CLUB = 0
COL_SPADE = 1
COL_HEART = 2
COL_DIAMOND = 3

# Card values
CARD_TWO = 2
CARD_THREE = 3
CARD_FOUR = 4
CARD_FIVE = 5
CARD_SIX = 6
CARD_SEVEN = 7
CARD_EIGHT = 8
CARD_NINE = 9
CARD_TEN = 10
CARD_JACK = 11
CARD_QUEEN = 12
CARD_KING = 13
CARD_ACE = 14

# Hand Rankings
RANK_HIGH_CARD = 0
RANK_ONE_PAIR = 1
RANK_TWO_PAIR = 2
RANK_THREE_OF_A_KIND = 3
RANK_STRAIGHT = 4
RANK_FLUSH = 5
RANK_FULL_HOUSE = 6
RANK_FOUR_OF_A_KIND = 7
RANK_STRAIGHT_FLUSH = 8
RANK_ROYAL_FLUSH = 9
