# Data Structure Constants
DATA_CARDLIST = 'cards'
DATA_CARD_VALUE = 'value'
DATA_CARD_COLOR = 'color'

# Constants
NUM_COLORS = 4
NUM_CARDS_PER_COLOR = 13
NUM_CARDS_PER_DECK = NUM_COLORS * NUM_CARDS_PER_COLOR

PID_IN_DECK_CARD = -2
PID_COMMUNITY_CARD = -1

# Color values
COL_CLUB = 0
COL_SPADE = 1
COL_HEART = 2
COL_DIAMOND = 3

# Card values
CARD_TWO = 0
CARD_THREE = 1
CARD_FOUR = 2
CARD_FIVE = 3
CARD_SIX = 4
CARD_SEVEN = 5
CARD_EIGHT = 6
CARD_NINE = 7
CARD_TEN = 8
CARD_JACK = 9
CARD_QUEEN = 10
CARD_KING = 11
CARD_ACE = 12

# Hand Rankings
RANK_HIGH_CARD = 0
RANK_ONE_PAIR = 1
RANK_TWO_PAIR = 2
RANK_THREE_OF_A_KIND = 3
RANK_STRAIGHT = 4
RANK_FLUSH = 5
RANK_FULL_HOUSE = 6
RANK_FOUR_OF_A_KIND = 7
RANK_STRAIGHT_FLUSH = 8
RANK_ROYAL_FLUSH = 9
